---
language: ruby
cache: bundler
rvm:
- 2.6.6
env:
  global:
  - BUNDLE_WITH=qpid_proton
addons:
  postgresql: '10'
before_install: source ${TRAVIS_BUILD_DIR}/tools/ci/before_install.sh
install: bin/setup
after_script: bin/ci/after_script
dist: bionic
