---
# Playbook Inputs:
# id (string) floating ip id

- name: Remove Floating Ip
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    entity_type: FloatingIp
  roles:
    - remove_entity
